### ISSUE TITLE
trouble with linking  Postgresql database to the setup 

### ISSUE THREAD

**Issue by urstrulykkr** [PyAr/PyZombis#12]
I found difficulty in creating a project DB for the Runestone project.
It is not getting back with assigned project_name (given earlier) when asked for.
Help wanted..

**Comment by gurupratap-matharu** [comment]
@urstrulykkr 

There is postgres configuration that you need for this project.

Make sure you do the following
1. Create a virtual envrionment and activate it everytime working on this project
2. Runestone merely converts the rst files to html and runs them on local server
3. Files are stored locally in the _sources folder
4. See @reingart post on setting up runestone step-by-step

If you still have doubts paste an image or upload a text file with your terminal log.

**Comment by urstrulykkr** [comment]
Thanks for the help @gurupratap-matharu . I shall surely have a look at this. 
If this solves the issue, I would certainly close this issue #12
