### ISSUE TITLE
Reto 1 falla por syntaxis de json (request a API externa)

### ISSUE THREAD

**Issue by reingart** [PyAr/PyZombis#197]
Error en https://pyar.github.io/PyZombis/main/challenges/Reto01.html
```
ExternalError: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data on line 8
```

Aparentemente no puede descargar de la API de universidades un json válido.
El error se puede ver en la consola del inspector del browser:

Firefox:
````
Bloqueado al cargar contenido de visualización mixto "http://universities.hipolabs.com/search"
````

Chrome:
```
Mixed Content: The page at 'https://pyar.github.io/PyZombis/main/challenges/Reto01.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://universities.hipolabs.com/search'. This request has been blocked; the content must be served over HTTPS.
```

https://universities.hipolabs.com/search no funciona, por lo que tendríamos que buscar otra API que funcione por https y permita bajar ciudades
Plan B: guardar el json de ciudades en un archivo en nuestra propia página (adjunto al ejercicio), para no tener que descargarla

**Comment by shivamshan** [comment]
@reingart I have replaced the failing API with a more configurable API which allows users to select cities of a particular country and state. Please review if the new API is acceptable or not. The concerned PR #199 .
