### ISSUE TITLE
Python integer division example [TWP40]

### ISSUE THREAD

**Issue by reingart** [PyAr/PyZombis#211]
The lecture has a C example
http://pyar.github.io/PyZombis/master/lectures/TWP40/TWP40_12.html

Ad an example in python with `//`
See https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex 

Add E2E Playwright test

**Comment by sujith-rek** [comment]
Hey,
I'd like to work on this
please assign it to me

**Comment by sitamgithub-MSIT** [comment]
If the issue is still not resolved, I'd like to work on this
please assign it to me
