### ISSUE TITLE
Translating Lectures to Spanish

### ISSUE THREAD

**Issue by IronVenom** [PyAr/PyZombis#22]
Translating lectures to Spanish using Sphinx Internationalization, and relevant tools.

**Comment by D3f0** [comment]
What are your plans on this @IronVenom ? Automated script?

**Comment by IronVenom** [comment]
I have added po files along with the translated Spanish strings and mo files for the same for all the lectures. There is some issue regarding the execution of build command as it is not being able to detect the mo files; I have filed an issue with the Sphinx repository regarding the same -
sphinx-doc/sphinx#659
po and mo files -
https://github.com/IronVenom/PyZombis/tree/translations/locale/es/LC_MESSAGES

Update - I have tried to make a different project using sphinx, deleted the multiple conf.py files and added as required. Now, the I am encountering the following exception -
```
Exception occurred:
  File "c:\users\atharva\envs\gsoc\lib\site-packages\docutils\nodes.py", line 1367, in set_duplicate_name_id
    old_node = self.ids[old_id]
KeyError: 'operadores-relacionais'
```
I have added this problem to the above issue and requested the repository collaborator for help. Some people before have also faced this issue, and I am not able to find a way around it except to mess with the nodes.py files, but I dont want to do that as it seems to have a lot of effects on the build.
Please suggest as to how to proceed.

**Comment by y-martinez** [comment]
Hi! @reingart or @D3f0  I updated the lecture TWP05 with an improvement in its redaction also translating words from Portuguese, can you review it, this PR close part of this issue
