### ISSUE TITLE
Poll in each chapter to rate course contents

### ISSUE THREAD

**Issue by reingart** [PyAr/PyZombis#241]
To get feedback we should have a simple poll at the end of each chapter

```
.. poll:: poll-ex1
   :scale: 10
   :allowcomment:

   En una escala del 1 (a mejorar) al 10 (excelente), 
   ¿como calificaría este cápitulo?
```
Documentation:
https://runestone.academy/ns/books/published/authorguide/directives/polls.html

**Comment by souviksenapati** [comment]
Hey @reingart is the issue still open may i work on this ?
