### ISSUE TITLE
Offline history / save / progress feature (JS local storage)

### ISSUE THREAD

**Issue by reingart** [PyAr/PyZombis#251]
Instead of making AJAX requests, we could store user code and progress directly in the browser's local storage.

This will allow students to work in the course offline or with bad internet connection.

For example, in some rural areas with limited connectivity or schools that don't have proper infrastructure to deploy a webserver, this will be ideal.

This also will allow to scale many users and support downtime of servers.

See #250 for the current AJAX calls being done to the REST API, we could hook there and do both (save to local storage and make remote request if network is available)

**Comment by sujith-rek** [comment]
@reingart   in this issue we only need to save
  progress of the activecode & codelens ?
  so that when the user comes back, his progress will be restored i.e. all the code he wrote will be shown?

**Comment by NicolasSandoval** [comment]
Closed this as completed in #281

**Comment by NicolasSandoval** [comment]
Closed this as completed in #281
