### ISSUE TITLE
Fix/Rewrite Examples to Embrace Runestone Available Python Features

### ISSUE THREAD

**Issue by IronVenom** [PyAr/PyZombis#26]
I am facing the following 2 issues after finishing work on the examples -

1. I am not able to create interactive examples in the case of a bit advanced examples which require the use of external libraries like urllib, pygame, tkinter, etc. using the activecode component as it doesn't seem to work after the build is made. I have tried to make the examples using activecode , it is not working.

2. When an example needs to read data from a .txt file, we need to use the Datafile component so as to make the example interactive, as the activecode reads data from it. But when I am using it, it is giving me the following error-

```
Unable to save to source_code table in datafile__init__.py. Possible problems:
  1. dburl or course_id are not set in conf.py for your book
  2. unable to connect to the database using dburl

This should only affect the grading interface. Everything else should be fine.`
```
And the build cannot be made when we use the datafile component

**Comment by D3f0** [comment]
@IronVenom this ticket should be into 2 or 3 tickets with specific problems.
