### ISSUE TITLE
Deploy Server with Course

### ISSUE THREAD

**Issue by D3f0** [PyAr/PyZombis#31]
It should look like this https://runestone.academy/runestone/default/user/login?_next=/runestone/default/index
The users should be able to Sing Up and Log In and store their grades.
In the future is expected to be automatically built from each git commit. This should be a Python script.

**Comment by D3f0** [comment]
The organization will provide the cloud resources. This is necessary for getting more feedback from the community.

**Comment by bnmnetp** [comment]
If you are interested, I would be happy to host this on Runestone.academy for you.

Brad

**Comment by IronVenom** [comment]
@bnmnetp Thanks! Yeah, I am interested. That would help a lot.
