### ISSUE TITLE
Fix starbuzz python exercise

### ISSUE THREAD

**Issue by reingart** [PyAr/PyZombis#61]
The example is broken:

http://pyar.github.io/PyZombis/lectures/TWP33.html#codigo-starbuzz-actual

![starbuzz](https://user-images.githubusercontent.com/1041385/111569643-d2142a80-8781-11eb-9d9f-a2e282aad2bd.png)

Beside the trivial typo causing the ImportError (and other two related to old Python2 issues), the code has a underlying problem that prevents running it in the student's browser.

Please fix the source code with valid python code that at least work in a terminal (or idle).
If you can, submit also a solution or alternative for the root cause.

**Comment by chazuttu** [comment]
![Screenshot (415)](https://user-images.githubusercontent.com/73628133/111789052-c3935380-88e6-11eb-8000-c392a3719940.png)
I tried to solve this issue but I am getting this error

**Comment by reingart** [comment]
Hi @chazuttu! 
You cannot run .rst files directly in python.
You need to copy just the python code in a .py if you want to use Visual Studio.
I recommend you to use our online version of the course, where you can edit directly the code and run it with the same web interpreter (no need to install anything in your machine): 
http://pyar.github.io/PyZombis/lectures/TWP33.html#codigo-starbuzz-actual

**Comment by chazuttu** [comment]
@reingart okk thanks a lot. I will try to do it!!

**Comment by chazuttu** [comment]
I had run this code and its successfully running. 
![Screenshot (420)](https://user-images.githubusercontent.com/73628133/111859273-99cd4180-8965-11eb-8cf9-11c08208908d.png)

But on the online version of the course of python argentina its giving errors:
![Screenshot (422)](https://user-images.githubusercontent.com/73628133/111859308-ef095300-8965-11eb-97bb-ec3403c20e3a.png)
urllib.request is not supported

**Comment by reingart** [comment]
Great advance!

Where are you running that?

Our online version does support urllib
Please test it here:
http://pyar.github.io/PyZombis/lectures/TWP33.html#codigo-starbuzz-actual

**Comment by LeoCumpli21** [comment]
Hi! This code works in Visual Studio

![urllibSs](https://user-images.githubusercontent.com/80920858/111882147-81ffb880-8979-11eb-9aa4-20bd04c0d2ba.PNG)

However, when run in Runestone it causes an error.

![errorRune](https://user-images.githubusercontent.com/80920858/111882198-ef134e00-8979-11eb-80e0-4e22df0de160.PNG)

**Comment by chazuttu** [comment]
I have tried it in same link ,it runs but when I click "show codelens " then it shows import error that it doesnt support urllib. 
My other question was that if we run it on the online version of python argentina , how we are going to generate pull request as my code runs now on online course!!

**Comment by chazuttu** [comment]
> Hi! This code works in Visual Studio
> 
> ![urllibSs](https://user-images.githubusercontent.com/80920858/111882147-81ffb880-8979-11eb-9aa4-20bd04c0d2ba.PNG)
> 
> However, when run in Runestone it causes an error.
> 
> ![errorRune](https://user-images.githubusercontent.com/80920858/111882198-ef134e00-8979-11eb-80e0-4e22df0de160.PNG)

I dont think so because I cloned this project on vs code but we cant edit .rst files , also if you create .py file and run it there ..its going to show error.

**Comment by y-martinez** [comment]
Hi @reingart I tried so many ways to make work the code so many variations and nothing, I cloned the code and ran it locally but just as @chazuttu and @LeoCumpli21 mention, the error appears when running the code on the environment, I did other tests using a more recent version of `runestone`, specifically the one that appears in this [link](https://runestone.academy/runestone/books/published/py4e-int/network/retrievingwebpageswithurllib.html), and the code works perfectly as in the Python terminal, so I have the theory that it is the Python version that runs in that `runestone` version, or the `runestone` itself

**Version of PyZombis**
![Screenshot from 2021-03-20 15-17-09](https://user-images.githubusercontent.com/6761059/111883080-6f907980-898f-11eb-9522-229bc925775c.png)

**Version of Runestone page**
![Screenshot from 2021-03-20 15-16-40](https://user-images.githubusercontent.com/6761059/111883081-70c1a680-898f-11eb-9e10-fca083694fdd.png)

**Comment by reingart** [comment]
You can remove `.decode("utf8")` and it will not throw the error, but will have another issue (the idea of this ticket is to analyze that).

The version of PyZombis uses a online interpreter (skulpt "3.2.0") that is different from standalone python and has some limitations.
The version of py4e-int seems to be using a full server-side interpreter (python 3.7.5)

The goal would be fix the code using the online web interpreter, if possible, or give alternatives.

A more complete exercise would be to fix the Facebook API examples in http://pyar.github.io/PyZombis/lectures/TWP45.html

**Comment by y-martinez** [comment]
Hi! @reingart I made a PR with an approach, please can you review it? :smile:

**Comment by LeoCumpli21** [comment]
Hi @reingart 

I updated my PR with an alternative to urllib.request. I hope you can review it.
[https://github.com/PyAr/PyZombis/pull/62#issue-596976482](url)

**Comment by chazuttu** [comment]
I have made a pull request with a different approach which will close this issue. Please review it @reingart 
https://github.com/PyAr/PyZombis/pull/65

**Comment by chazuttu** [comment]
[https://github.com/PyAr/PyZombis/pull/65](url)

**Comment by chazuttu** [comment]
> You can remove `.decode("utf8")` and it will not throw the error, but will have another issue (the idea of this ticket is to analyze that).
> 
> The version of PyZombis uses a online interpreter (skulpt "3.2.0") that is different from standalone python and has some limitations.
> The version of py4e-int seems to be using a full server-side interpreter (python 3.7.5)
> 
> The goal would be fix the code using the online web interpreter, if possible, or give alternatives.
> 
> A more complete exercise would be to fix the Facebook API examples in http://pyar.github.io/PyZombis/lectures/TWP45.html

#65
