### ISSUE TITLE
Adapt assignments to use Runestone's ActiveCode

### ISSUE THREAD

**Issue by reingart** [PyAr/PyZombis#7]
The simple [quiz](https://github.com/PyAr/PyZombis/tree/master/quiz) (simple exercises) should be converted to interactive python scripts using [ActiveCode](http://runestoneinteractive.org/build/html/directives/activecode.html) Runestone's plugin.

In the [original course](https://www.pycursos.com/python-para-zumbis/), assignments should be downloaded and executed with a local python environment.

Runestone solves this thanks to an embebed python interpreter in the browser, so it doesn't have any annonyance, being fast and scalable.

**Comment by reingart** [comment]
For a complete list of assignments see: http://bit.ly/pyzombis

Some Examples:
 * https://www.dropbox.com/home/python-zumbis?preview=Lista+de+Exerc%C3%ADcios+III+Desafio+Python+para+Zumbis.pdf (5 exercises)
 * https://www.dropbox.com/home/python-zumbis?preview=Lista+de+Exerc%C3%ADcios+IV+Python+para+Zumbis.pdf (5 exercises)

* https://www.dropbox.com/home/python-zumbis?preview=Lista+de+Exerc%C3%ADcios+XIV+Python+para+Zumbis.pdf
* https://www.dropbox.com/home/python-zumbis?preview=Lista+Extra+Python+para+Zumbis+(DESAFIO)+cont.pdf

NOTE: many exercises will require implementing a minimal "unit-test" so it can be automatically graded

**Comment by IronVenom** [comment]
I think we should also add a report card, where we can showcase each of the user's marks and points. This will help in building up motivation to perform well and study more. This can be just a static page ( made using PHP or JS), linked with a dbms like MySQL.

**Comment by IronVenom** [comment]
Probably a leaderboard based page, with login credentials same as the Runestone books.

**Comment by IronVenom** [comment]
Probably a leaderboard based page, with login credentials same as the Runestone books.
